[project]
name = 'barnacle_contracts'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.file_encryption]
path = 'contracts/file_encryption.clar'
clarity_version = 2
epoch = 2.5

[contracts.ownership_transfer_wallet]
path = 'contracts/ownership_transfer_wallet.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
